version: '3.9'
services:
  db:
    image: "postgres:13-alpine"
    container_name: postgres-server
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food
      TZ: Asia/Ulaanbaatar
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  foodorder:
    image: foodorder
    container_name: food-prod
    ports:
      - "8082:8082"
    restart: always
    environment:
      DB_CONNECTION: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: food
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APP_PORT: 8082
      APP_MIGRATE: false
      APP_SEED: false
      DB_DEBUG: false
      JWT_SECRET: BIzaSyBUEDlwdKQ0AZOnHOkZv2MIw0GlRjql6V4
      TZ: Asia/Ulaanbaatar
    depends_on:
      - db
    volumes:
      - ./public:/home/ebarimtuser/app/public
      - ./app:/home/ebarimtuser/app/app
      - ./routes:/home/ebarimtuser/app/routes
      - ./bootstrap:/home/ebarimtuser/app/bootstrap
      - ./lambda:/home/ebarimtuser/app/lambda
      - ./go.mod:/home/ebarimtuser/app/go.mod
      - ./go.sum:/home/ebarimtuser/app/go.sum
      - ./lambda.json:/home/ebarimtuser/app/lambda.json
      - ./start.sh:/home/ebarimtuser/app/start.sh
      - ./libPosAPI.so:/home/ebarimtuser/app/libPosAPI.so #./libPosAPI.so path your so file
#      - ./ebarimt_data:/home/ebarimtuser/.vatps
    labels:
      - "traefik.http.routers.foodorder.tls=true"
      - "traefik.http.routers.foodorder.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      - "traefik.http.routers.foodorder.rule=Host(`foodorder.tavanbogd.mn`)"
      - "traefik.http.services.foodorder.loadbalancer.server.port=8082"
      - "traefik.http.middlewares.foodorder_compress.compress=true"
      - "traefik.http.routers.foodorder.middlewares=foodorder_compress"

networks:
  traefik-net:
    driver: overlay
    ipam:
      driver: bridge
